const styles = {
  layout: {
    minHeight: "100vh",
    width: "100%",
    background: "#f4f7fb",
    color: "#111827",
    fontFamily: "Aptos, 'Segoe UI', sans-serif",
  },
  main: {
    width: "calc(100% - 250px)",
    minHeight: "100vh",
    marginLeft: "250px",
    padding: "36px 40px 45px",
  },
  page: {
    width: "100%",
    minHeight: "100%",
    padding: "0",
    boxSizing: "border-box",
  },
  container: {
    width: "100%",
    maxWidth: "1440px",
    minWidth: 0,
    margin: "0 auto",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "20px",
    marginBottom: "24px",
  },
  title: {
    margin: 0,
    color: "#111827",
    fontSize: "30px",
    lineHeight: 1.2,
    fontWeight: "750",
  },
  subtitle: {
    margin: "8px 0 0",
    color: "#667085",
    fontSize: "14px",
  },
  count: {
    flexShrink: 0,
    padding: "8px 12px",
    border: "1px solid #dbeafe",
    borderRadius: "20px",
    background: "#eff6ff",
    color: "#2563eb",
    fontSize: "12px",
    fontWeight: "700",
    whiteSpace: "nowrap",
  },
  error: {
    padding: "14px 16px",
    marginBottom: "18px",
    border: "1px solid #fecdca",
    borderRadius: "10px",
    background: "#fff1f2",
    color: "#b42318",
    fontSize: "14px",
    lineHeight: 1.5,
  },
  info: {
    padding: "40px 20px",
    border: "1px solid #e4e7ec",
    borderRadius: "14px",
    background: "#ffffff",
    color: "#667085",
    textAlign: "center",
    boxShadow: "0 5px 20px rgba(15,23,42,0.055)",
  },
  tableBox: {
    width: "100%",
    maxHeight: "min(68vh, 680px)",
    overflowX: "auto",
    overflowY: "auto",
    overscrollBehavior: "contain",
    WebkitOverflowScrolling: "touch",
    border: "1px solid #e4e7ec",
    borderRadius: "14px",
    background: "#ffffff",
    boxShadow: "0 5px 20px rgba(15,23,42,0.055)",
  },
  table: {
    width: "100%",
    minWidth: "950px",
    tableLayout: "fixed",
    borderCollapse: "collapse",
  },
  th: {
    position: "sticky",
    top: 0,
    zIndex: 1,
    padding: "14px 16px",
    background: "#f8fafc",
    borderBottom: "1px solid #eaecf0",
    color: "#667085",
    fontSize: "10px",
    fontWeight: "750",
    letterSpacing: "0.6px",
    textAlign: "left",
    whiteSpace: "nowrap",
  },
  td: {
    padding: "15px 16px",
    borderBottom: "1px solid #f0f2f5",
    color: "#475467",
    fontSize: "13px",
    whiteSpace: "nowrap",
  },
  amount: {
    padding: "15px 16px",
    borderBottom: "1px solid #f0f2f5",
    color: "#101828",
    fontSize: "13px",
    fontWeight: "750",
    whiteSpace: "nowrap",
  },
};

export default styles;