const styles = {
  container: {
    minHeight: "100vh",
    background: "#f4f6f8",
    padding: "45px 20px",
    color: "#111827",
    boxSizing: "border-box",
  },
  card: {
    width: "100%",
    maxWidth: "560px",
    margin: "0 auto",
    background: "#ffffff",
    padding: "32px",
    borderRadius: "16px",
    boxSizing: "border-box",
    boxShadow: "0 10px 30px rgba(0, 0, 0, 0.08)",
    border: "1px solid #e5e7eb",
  },
  header: {
    marginBottom: "28px",
    textAlign: "center",
  },
  heading: {
    margin: "0 0 7px",
    color: "#111827",
    fontSize: "28px",
    fontWeight: "700",
  },
  subtitle: {
    margin: 0,
    color: "#6b7280",
    fontSize: "14px",
  },
  form: {
    width: "100%",
  },
  label: {
    display: "block",
    marginBottom: "7px",
    color: "#111827",
    fontSize: "14px",
    fontWeight: "600",
  },
  input: {
    width: "100%",
    height: "46px",
    padding: "0 13px",
    marginBottom: "18px",
    boxSizing: "border-box",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    background: "#ffffff",
    color: "#111827",
    fontSize: "14px",
    outline: "none",
  },
  priceBox: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "14px 16px",
    marginBottom: "20px",
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
    borderRadius: "9px",
  },
  priceLabel: {
    color: "#374151",
    fontSize: "14px",
    fontWeight: "600",
  },
  price: {
    color: "#111827",
    fontSize: "19px",
    fontWeight: "700",
  },
  message: {
    margin: "5px 0 20px",
    padding: "12px 14px",
    background: "#f3f4f6",
    color: "#111827",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    fontSize: "14px",
    lineHeight: "1.5",
  },
  buttons: {
    display: "flex",
    gap: "12px",
    marginTop: "5px",
  },
  cash: {
    flex: 1,
    height: "46px",
    padding: "0 15px",
    background: "#166534",
    color: "#ffffff",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "600",
  },
  payment: {
    flex: 1,
    height: "46px",
    padding: "0 15px",
    background: "#1d4ed8",
    color: "#ffffff",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "600",
  },
};

export default styles;
